/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billingsystem;

import billingsystem.dao.SupplierDAO;
import billingsystem.model.SupplierModel;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class SupplierInformation extends javax.swing.JFrame {

    int fields = 0;
    float t = 0.0f;

    public SupplierInformation() {
        initComponents();
        total.setText("0.0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        suppliername = new javax.swing.JTextField();
        itemname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        itemcode = new javax.swing.JTextField();
        rate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mrp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        amtpaid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        qtyspinner = new javax.swing.JSpinner();
        reset = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        total = new javax.swing.JLabel();
        due = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Suppier Information");
        setLocation(new java.awt.Point(450, 150));
        setMinimumSize(new java.awt.Dimension(458, 617));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("Supplier Information");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Supplier Name");

        suppliername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        suppliername.setToolTipText("Please Enter Name.");
        suppliername.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        itemname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        itemname.setToolTipText("Please Enter Name.");
        itemname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Item Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Item Code");

        itemcode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        itemcode.setToolTipText("Please Enter Name.");
        itemcode.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        rate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rate.setToolTipText("Please Enter Name.");
        rate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rateFocusGained(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Rate ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("M R P");

        mrp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mrp.setToolTipText("Please Enter Name.");
        mrp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mrp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mrpFocusGained(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Quantity");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Total");

        amtpaid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        amtpaid.setToolTipText("Please Enter Name.");
        amtpaid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        amtpaid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                amtpaidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                amtpaidFocusLost(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Amount Paid");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Due");

        qtyspinner.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        qtyspinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        qtyspinner.setToolTipText("Enter Quantity");
        qtyspinner.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                qtyspinnerFocusLost(evt);
            }
        });

        reset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        reset.setText("Reset");
        reset.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                resetFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                resetFocusLost(evt);
            }
        });
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        reset.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                resetKeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Mobile");

        mobile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mobile.setToolTipText("Please Enter Name.");
        mobile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mobile.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mobileFocusGained(evt);
            }
        });

        submit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        submit.setText("Submit");
        submit.setToolTipText("ctrl+S");
        submit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                submitFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                submitFocusLost(evt);
            }
        });
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        submit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                submitKeyPressed(evt);
            }
        });

        total.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        due.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(suppliername, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(itemname, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(itemcode, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rate, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(mrp, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(qtyspinner, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(amtpaid, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(due, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(reset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(submit)
                                .addGap(15, 15, 15))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suppliername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtyspinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amtpaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(due, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reset)
                    .addComponent(submit))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resetFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resetFocusGained
        reset.setBackground(Color.decode("0x999999"));
    }//GEN-LAST:event_resetFocusGained

    private void resetFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_resetFocusLost
        reset.setBackground(Color.decode("0xF0F0F0"));
    }//GEN-LAST:event_resetFocusLost

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed

        this.rate.setText("" + 0.0);
        this.amtpaid.setText("" + 0.0);

        this.qtyspinner.setValue(0);
        this.due.setText("" + 0.0);
        this.mrp.setText("" + 0.0);
        this.total.setText("" + 0.0);
        this.suppliername.setText("");
        this.itemname.setText("");
        this.itemcode.setText("");
        this.mobile.setText("Nil");
    }//GEN-LAST:event_resetActionPerformed

    private void resetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_resetKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            this.rate.setText("" + 0.0);
            this.amtpaid.setText("" + 0.0);

            this.qtyspinner.setValue(0);
            this.due.setText("" + 0.0);
            this.mrp.setText("" + 0.0);
            this.total.setText("" + 0.0);
            this.suppliername.setText("");
            this.itemname.setText("");
            this.itemcode.setText("");
            this.mobile.setText("Nil");
        }
    }//GEN-LAST:event_resetKeyPressed

    private void submitFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_submitFocusGained
        submit.setBackground(Color.decode("0x999999"));
    }//GEN-LAST:event_submitFocusGained

    private void submitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_submitFocusLost
        submit.setBackground(Color.decode("0xF0F0F0"));
    }//GEN-LAST:event_submitFocusLost

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        SupplierModel supplierModel = new SupplierModel();

        String suppname = this.suppliername.getText();
        StringBuilder sb = new StringBuilder(suppname);
        sb.setCharAt(0, Character.toUpperCase(sb.charAt(0)));
        suppname = sb.toString();
        if (suppname.length() != 0) {
            fields++;
        }

        String mobile = this.mobile.getText();
        String regex = "[6-9][0-9]{9}";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(mobile);
        if (!mobile.equals("Nil")) {
            if (matcher.matches()) {
                fields++;
            }
        } else {
            mobile = "Nil";
            fields++;
        }

        String itemname = this.itemname.getText();
        StringBuilder sb1 = new StringBuilder(itemname);
        sb1.setCharAt(0, Character.toUpperCase(sb.charAt(0)));
        suppname = sb1.toString();
        if (itemname.length() != 0) {
            fields++;
        }

        String itemcode = this.itemcode.getText();
        if (itemcode.length() != 0) {
            fields++;
        } else {
            itemcode = "Nil";
            fields++;
        }

        float rate = Float.parseFloat(this.rate.getText());
        if (rate != 0) {
            fields++;
        }

        float mrp = Float.parseFloat(this.mrp.getText());
        if (mrp != 0) {
            fields++;
        }

        int qty = (int) this.qtyspinner.getValue();
        if (qty != 0) {
            fields++;
        }

        //rate =  Float.parseFloat(this.rate.getText());
        // qty = (int) this.qtyspinner.getValue();
        t = rate * qty;
        this.total.setText("" + t);

        float am = Float.parseFloat(this.amtpaid.getText());
        if (am != 0) {
            fields++;
        }

        float due = t - am;
        this.due.setText("" + due);

        Date d = new Date();
        SimpleDateFormat da = new SimpleDateFormat("dd/MM/yyyy");
        String date = da.format(d);

        supplierModel.setDate(date);
        supplierModel.setSuppliername(suppname);
        supplierModel.setMobile(mobile);
        supplierModel.setItemname(itemname);
        supplierModel.setItemcode(itemcode);
        supplierModel.setRate(rate);
        supplierModel.setMrp(mrp);
        supplierModel.setQty(qty);
        supplierModel.setTotal(t);
        supplierModel.setAmtpaid(am);
        supplierModel.setDue(due);

        if (SupplierDAO.submit(supplierModel) && fields == 8) {

            JOptionPane.showMessageDialog(this, "Data Submit.", "Submmision sucessful.", JOptionPane.INFORMATION_MESSAGE);
            fields = 0;

            //this.setVisible(false);
            this.rate.setText("" + 0.0);
            this.amtpaid.setText("" + 0.0);

            this.qtyspinner.setValue(0);
            this.due.setText("" + 0.0);
            this.mrp.setText("" + 0.0);
            this.total.setText("" + 0.0);
            this.suppliername.setText("");
            this.itemname.setText("");
            this.itemcode.setText("");
            this.mobile.setText("Nil");
        } else {
            JOptionPane.showMessageDialog(this, "Please Enter Appropriate Data.", "Submmision Falied.", JOptionPane.ERROR_MESSAGE);
              fields = 0;
              this.rate.setText("" + 0.0);
            this.amtpaid.setText("" + 0.0);

            this.qtyspinner.setValue(0);
            this.due.setText("" + 0.0);
            this.mrp.setText("" + 0.0);
            this.total.setText("" + 0.0);
            this.suppliername.setText("");
            this.itemname.setText("");
            this.itemcode.setText("");
            this.mobile.setText("Nil");
        }


    }//GEN-LAST:event_submitActionPerformed

    private void submitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_submitKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            SupplierModel supplierModel = new SupplierModel();

            String suppname = this.suppliername.getText();
            StringBuilder sb = new StringBuilder(suppname);
            sb.setCharAt(0, Character.toUpperCase(sb.charAt(0)));
            suppname = sb.toString();
            if (suppname.length() != 0) {
                fields++;
            }

            String mobile = this.mobile.getText();
            String regex = "[6-9][0-9]{9}";
            Pattern pattern = Pattern.compile(regex);
            Matcher matcher = pattern.matcher(mobile);
            if (!mobile.equals("Nil")) {
                if (matcher.matches()) {
                    fields++;
                }
            } else {
                mobile = "Nil";
                fields++;
            }

            String itemname = this.itemname.getText();
            StringBuilder sb1 = new StringBuilder(itemname);
            sb1.setCharAt(0, Character.toUpperCase(sb.charAt(0)));
            itemname = sb1.toString();
            if (itemname.length() != 0) {
                fields++;
            }

            String itemcode = this.itemcode.getText();
            if (itemcode.length() != 0) {
                fields++;
            } else {
                itemcode = "Nil";
                fields++;
            }

            float rate = Float.parseFloat(this.rate.getText());
            if (rate != 0) {
                fields++;
            }

            float mrp = Float.parseFloat(this.mrp.getText());
            if (mrp != 0) {
                fields++;
            }

            int qty = (int) this.qtyspinner.getValue();
            if (qty != 0) {
                fields++;
            }

            //rate =  Float.parseFloat(this.rate.getText());
            // qty = (int) this.qtyspinner.getValue();
            t = rate * qty;
            this.total.setText("" + t);

            float am = Float.parseFloat(this.amtpaid.getText());
            if (am != 0) {
                fields++;
            }

            float due = t - am;
            this.due.setText("" + due);

            Date d = new Date();
            SimpleDateFormat da = new SimpleDateFormat("dd/MM/yyyy");
            String date = da.format(d);

            supplierModel.setDate(date);
            supplierModel.setSuppliername(suppname);
            supplierModel.setMobile(mobile);
            supplierModel.setItemname(itemname);
            supplierModel.setItemcode(itemcode);
            supplierModel.setRate(rate);
            supplierModel.setMrp(mrp);
            supplierModel.setQty(qty);
            supplierModel.setTotal(t);
            supplierModel.setAmtpaid(am);
            supplierModel.setDue(due);

            if (SupplierDAO.submit(supplierModel) && fields == 8) {

                JOptionPane.showMessageDialog(this, "Data Submit.", "Submmision sucessful.", JOptionPane.INFORMATION_MESSAGE);
                fields = 0;

                // this.setVisible(false);
                this.rate.setText("" + 0.0);
                this.amtpaid.setText("" + 0.0);

                this.qtyspinner.setValue(0);
                this.due.setText("" + 0.0);
                this.mrp.setText("" + 0.0);
                this.total.setText("" + 0.0);
                this.suppliername.setText("");
                this.itemname.setText("");
                this.itemcode.setText("");
                this.mobile.setText("Nil");
            } else {
                JOptionPane.showMessageDialog(this, "Please Enter Appropriate Data.", "Submmision Falied.", JOptionPane.ERROR_MESSAGE);

                fields = 0;
              this.rate.setText("" + 0.0);
            this.amtpaid.setText("" + 0.0);

            this.qtyspinner.setValue(0);
            this.due.setText("" + 0.0);
            this.mrp.setText("" + 0.0);
            this.total.setText("" + 0.0);
            this.suppliername.setText("");
            this.itemname.setText("");
            this.itemcode.setText("");
            this.mobile.setText("Nil");
            }

        }
    }//GEN-LAST:event_submitKeyPressed

    private void amtpaidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_amtpaidFocusGained
        amtpaid.setText("");
        float rate = Float.parseFloat(this.rate.getText());
        int qty = (int) this.qtyspinner.getValue();
        float total = rate * qty;
        this.total.setText("" + total);

    }//GEN-LAST:event_amtpaidFocusGained

    private void amtpaidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_amtpaidFocusLost
        float total = Float.parseFloat(this.total.getText());
        float amt = Float.parseFloat(this.amtpaid.getText());
        float due = total - amt;
        this.due.setText("" + due);
        this.submit.requestFocus();

    }//GEN-LAST:event_amtpaidFocusLost

    private void qtyspinnerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qtyspinnerFocusLost
        float rate = Float.parseFloat(this.rate.getText());
        int qty = (int) this.qtyspinner.getValue();
        float total = rate * qty;
        this.total.setText("" + total);
    }//GEN-LAST:event_qtyspinnerFocusLost

    private void mobileFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mobileFocusGained
      mobile.setText("");
    }//GEN-LAST:event_mobileFocusGained

    private void rateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rateFocusGained
       rate.setText("");
    }//GEN-LAST:event_rateFocusGained

    private void mrpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mrpFocusGained
         mrp.setText("");
    }//GEN-LAST:event_mrpFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupplierInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupplierInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupplierInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupplierInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupplierInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amtpaid;
    private javax.swing.JLabel due;
    private javax.swing.JTextField itemcode;
    private javax.swing.JTextField itemname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField mrp;
    private javax.swing.JSpinner qtyspinner;
    private javax.swing.JTextField rate;
    private javax.swing.JButton reset;
    private javax.swing.JButton submit;
    private javax.swing.JTextField suppliername;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
